cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
          name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop12v/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    """
    Создание в базе данных таблицы продуктов

    Параметры:
    Категория продуктов
    Название
    Флаг
    Фото товара
    Описание
    Цена
    Доступен или нет
    Дата создания
    Дата обновления
    """
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('name',)
        index_together = (('id','slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class Comment(models.Model):
    """
    Класс отвечает за создание в базе данных таблицы комментариев

    Пост опубликованный пост, к которому относится комментарий
    Имя того кто создал комментарий
    Емейл человека который создал комментарий
    Тело комментария
    Дата создания комментария
    Дата обновления комментария
    Дата когда комментарий был опубликован
    """
    post = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments',verbose_name=u"Пользователь")
    name = models.CharField(max_length=80,verbose_name=u"Имя")
    email = models.EmailField()
    body = models.TextField(verbose_name=u"Текст комментария")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 6)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)

    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

shop/forms.py
from .models import Comment
from django import forms



class CommentForm(forms.ModelForm):
    """Класс отвечает за создание формы комментария

    Поля:
    Имя того кто пишет комментарии
    Емэйл
    Тело комметнария
    """
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    """Добавление товара в корзину"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    """Удаление товара из корзины"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    """Отображение товара, находящегося в корзине.
    Отображение корзины покупок.
    """
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Category, Product, Comment
from cart.forms import CartAddProductForm
from .forms import CommentForm


def product_list(request, category_slug=None):
    """
    Функция отображения списка продуктов

    Отвечает за отображение списка продуктов на странице
    Благодаря пагинации количество продуктов отображает в количестве 3
    штук на одной странице.
    """
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    paginator = Paginator(products, 3)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/product/list.html',
                  {'page': page,
                   'category': category,
                   'categories': categories,
                   'products': products})



def product_detail(request, id, slug):
    """
    Функция отображения информации о продукте

    Отвечает за детальное отображение информации о продукте
    а также за отображение комментариев о данном продукте.
    """
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()


    # Список активных комментариев для этой статьи.
    comments = product.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
    # Пользователь отправил комментарий.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в базе данных.
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье.
            new_comment.post = product
            # Сохраняем комментарий в базе данных.
            new_comment.save()
    else:
        comment_form = CommentForm()


    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form':cart_product_form,
                                                        'comments': comments,
                                                        'new_comment': new_comment,
                                                        'comment_form': comment_form,
                                                        })

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}Корзина покупок{% endblock %}
{% block content %}
    <h1>Ваша корзина покупок</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Продукт</th>
            <th>Количество</th>
            <th>Очистить</th>
            <th>Цена товара</th>
            <th>Общая цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}
 {% else %}{% static "img/no_image.png" %}{% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>


                    <td>
                        <form action="{% url "cart:cart_add" product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Обновить">
                            {% csrf_token %}
                        </form>


                    </td>


                    <td><a href="{% url "cart:cart_remove" product.id %}">Очистить</a></td>
                    <td class="num">{{ item.price }} р.</td>
                    <td class="num">{{ item.total_price }} р.</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Общая сумма</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} р.</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">Продолжить покупки</a>
        <a href="#" class="button">Проверить покупки</a>
    </p>
{% endblock %}

shop/templates/pagination.html
<div class="pagination">
<span class="step-links">
{% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}"><h3><b>Предыдущая</b></h3></a>
{% endif %}
    <span class="current"><h3><b>
  Страница {{ page.number }} из {{ page.paginator.num_pages }}.
    </b></h3>
</span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}"><h3><b>Следующая</b></h3></a>
    {% endif %}
</span>
</div>

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Online магазин Мастер 12 вольт{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<div id="header">
    <a href="/" class="logo"><strong>Мастер 12 Вольт. Автосигнализации в Гродно.</strong></a>
    <p><br></p>
    <h4>Все позиции исключительно под заказ. Осуществляем установку всего перечня электрооборудования.</h4>
    <h4>Наши специалисты прошли обучение в Германии.</h4>
    <h4>Официальная гарантия 12 месяцев на установку. Поможем подобрать оборудование на ваш автомобиль.</h4>
    <h4>Адрес: г. Гродно, улица Карского, 4в. моб. тел. +37529 5312123 (мтс)</h4>
</div>

<div id="subheader">
    <div class="cart">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Ваша корзина:
                <a href="{% url "cart:cart_detail" %}">товаров:
                    {{ total_items }} , сумма:
                    {{ cart.get_total_price }} р.
                </a>
            {% else %}
                Ваша корзина пуста.
            {% endif %}
        {% endwith %}


    </div>
</div>
<div id="content">

    {% block content %}{% endblock %}
</div>
</body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {{ product.name }}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}
 {% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2>
            <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>
        </h2>
        <p class="price">{{ product.price }} рублей</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">

            {{ cart_product_form }}
            {% csrf_token %}
            <input type='submit' value='Добавить в корзину'>
        </form>


        {{ product.description|linebreaks }}
        {% with comments.count as total_comments %}
            <h2>Количество комментариев: {{ total_comments }} </h2>
        {% endwith %}

        {% for comment in comments %}
            <div class="comment">
                <p class="info">
                    Прокомментировано: {{ forloop.counter }}  {{ comment.name }}
                    {{ comment.created }}
                </p>
                {{ comment.body|linebreaks }}
            </div>
        {% empty %}
            <p>Тут пока нет комментариев.</p>
        {% endfor %}

        {% if new_comment %}
            <h2>Ваш комментарий был добавлен.</h2>
        {% else %}
            <h2>Добавить новый комментарий:</h2>
            <form action="." method="post">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Добавить"></p>
            </form>
        {% endif %}
    <p>
        <br>
        <br>
    </p>

        <h4><b>Заказать товар можно по адресу: г. Гродно, улица Карского, 4в. моб. тел. +37529 5312123 (мтс)</b></h4>
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Продукты{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Категории</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">Все</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Продукты{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>

                <br>
                {{ product.price }} рублей
            </div>
        {% endfor %}

    </div>
    {% include "pagination.html" with page=products %}
<p><br></p>
<h4>ООО "Мастер 12 Вольт" г.Гродно, ул. Карского д.4в, УНП 590998538</h4>
    <p><br></p>
{% endblock %}